---
- hosts: all
  
  tasks:
  
    - name: Install IIS Server
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes

    - name: Create App Pool with .NET 4.0
      win_iis_webapppool:
        name: 'SitecoreAppPool'
        state: started
        attributes: managedRuntimeVersion:v4.0

    - name: Create physical directory
      win_file:
        path: C:\sites\Sitecore
        state: directory

    - name: Create physical directory
      win_file:
        path: C:\sites\logs
        state: directory
 
    - name: Create Sitecore IIS site
      win_iis_website:
        name: "Sitecore"
        state: started
        port: 80
        ip: 127.0.0.1
        hostname: sitecore1.sapient.com
        application_pool: "SitecoreAppPool"
        physical_path: c:\sites\Sitecore
        parameters: logfile.directory:c:\sites\logs
  
    - name: Bind Sitecore Website to 443 port
      win_iis_webbinding:
        name: Sitecore
        protocol: https
        port: 443
        state: present

    - name: Copy sample test page
      win_copy:
        src: /data/playbooks/index.html
        dest: c:\sites\Sitecore

    - name: Create a Sitecore virtual directory
      win_iis_virtualdirectory:
        name: app
        site: Sitecore
        state: present
        physical_path: c:\sites\Sitecore

    - name: Add IIS_IUSRS allow rights
      win_acl:
        path: c:\sites\Sitecore
        user: IIS_IUSRS
        rights: FullControl
        type: allow
        state: present
        inherit: ContainerInherit, ObjectInherit
        propagation: 'None'
