---
- hosts: all
  
  tasks:
  
     - name: Copy mongodb package to remote machine
       win_copy:
         src: /data/software/mongodb-win32-x86_64-enterprise-windows-64-3.4.4.zip
         dest: E:\

     - name: Extract mongodb package
       win_unzip:
         src: E:\mongodb-win32-x86_64-enterprise-windows-64-3.4.4.zip
         dest: E:\
         rm: true

     - name: Copy config file 
       win_copy:
         src: /data/playbooks/mongo.config
         dest: E:\mongodb

     - name: 
       win_shell: E:\mongodb\bin\mongod.exe --config E:\mongodb\mongo.config --install 
      # args:
       #   chdir: E:\mongodb\bin

     - name: 
       win_shell: net start mongod
